# DOCKERCOMPOSE for the POLICY REASONER GUI
#   by Tim Müller
# 
# Runs both the client webserver and Rust backend in a container.
# 


version: '3.6'
services:
  policy-reasoner-gui:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      target: backend
      tags:
      - policy-reasoner-gui:latest
    container_name: policy-reasoner-gui
    restart: always
    command: [ "--checker-address", "${CHECKER_ADDR:-http://host.docker.internal:3030}" ]
    volumes:
    - ${KEY_PATH:-./key}:/key
    ports:
    - 3001:3001

networks:
  default:
    name: policy-reasoner-gui
